language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk-ea

matrix:
  allow_failures:
    - jdk: oraclejdk10
    - jdk: oraclejdk-ea

# see https://github.com/travis-ci/travis-ci/issues/8408
before_install:
- unset _JAVA_OPTIONS

# use travis-ci docker based infrastructure
sudo: false

cache:
  directories:
    - $HOME/.m2

script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- mvn test -B
